In [2]:
import numpy as np
np.set_printoptions(suppress=True,precision=4)

In [3]:
price=np.array([100,107,102,110])

In [4]:
ret=price[1:]/price[:-1]-1

In [5]:
ret

array([ 0.07  , -0.0467,  0.0784])

In [6]:
100*(ret+1).prod()

109.99999999999999

In [8]:
log_return=np.log(price[1:]/price[:-1])
log_return

array([ 0.0677, -0.0479,  0.0755])

In [10]:
meanlog=log_return.mean()

In [11]:
meanlog

0.031770059934774955

In [14]:
100*np.exp(meanlog*3)

110.00000000000001

In [15]:
add=log_return.sum()
add

0.09531017980432487

In [16]:
100*np.exp(add)

110.00000000000001

In [17]:
pop=np.loadtxt('C:/Users/aheed/Desktop/SP500.csv', delimiter=",",usecols=1)

In [18]:
pop.size

500

In [20]:
pop=pop*100

In [21]:
pop.max()

386.7155664221679

In [22]:
pop.min()

-51.30060027705095

In [24]:
range=pop.ptp()
range

438.01616669921884

In [25]:
pop.max()-pop.min()

438.01616669921884

In [26]:
sample=np.loadtxt('C:/Users/aheed/Desktop/sample.csv', delimiter=",",usecols=1)

In [27]:
sample=sample*100

In [28]:
np.max(sample)

132.30016313213704

In [29]:
np.min(sample)

-12.747464992757129

In [30]:
np.max(sample)-np.min(sample)

145.04762812489417

In [31]:
s=sample.ptp()
s

145.04762812489417

# VARIANCE AND STANDARD DEVIATION

VARIANCE

In [33]:
pop.var()

962.631408916871

In [34]:
np.var(sample)

911.4389576826238

In [35]:
np.var(sample,ddof=1)

930.0397527373713

STANDARD DEVIATION

In [37]:
pop.std()

31.026301889153192

In [39]:
sample.std(ddof=1)

30.496553128794265

# PERCENTILES

VALUE BELOW WHICH GIVEN % OF OBSERVATIONS FALL

FOR EG 20TH PERCENTILE: 20% OF OBSERVATION FOUND IN THIS 

interpretation: 50% of returns are below 18.15

In [41]:
np.median(pop)

18.158807954190955

In [43]:
np.percentile(pop,95)

65.84576599196505

In [44]:
np.percentile(pop,[25,75])

array([ 4.2101, 35.5532])

4.2% and 35.5% returns lie in range of 25th and 75th percentile, aka 50% fall in this range and 25% are below 4.2 and 25% are above 35.2

In [45]:
np.percentile(pop,[5,95])

array([-14.4503,  65.8458])

90% observations are in this range

In [46]:
np.percentile(pop,[2.5,97.5])

array([-23.4189,  81.1018])

95% values lie in this