# NESTED LISTS

In [1]:
proj1=[-200,120,44,55,24,50]
proj2=[-1000,400,245,249,400]
proj3=[-120,22,44,23]

In [2]:
all_proj=[proj1,proj2,proj3]

In [3]:
all_proj

[[-200, 120, 44, 55, 24, 50], [-1000, 400, 245, 249, 400], [-120, 22, 44, 23]]

In [4]:
all_proj[0]

[-200, 120, 44, 55, 24, 50]

In [6]:
all_proj[-1]

[-120, 22, 44, 23]

In [7]:
all_proj[0][0]

-200

In [8]:
all_proj[:2]

[[-200, 120, 44, 55, 24, 50], [-1000, 400, 245, 249, 400]]

In [9]:
all_proj[1:]

[[-1000, 400, 245, 249, 400], [-120, 22, 44, 23]]

In [10]:
all_proj[:-2]

[[-200, 120, 44, 55, 24, 50]]

In [11]:
all_proj[:][0]

[-200, 120, 44, 55, 24, 50]

initial investment of all projects:

In [12]:
initial=[]
for i in all_proj:
    initial.append(i[0])

In [13]:
initial

[-200, -1000, -120]

# 2d numpy array

In [14]:
import numpy as np

In [37]:
cf1=[-200,50,44,42,14,63]
cf2=[-120,24,51,5,12,35]
cf3=[-1000,245,241,300,45,58]
nl=[cf1,cf2,cf3]

In [44]:
nl

[[-200, 50, 44, 42, 14, 63],
 [-120, 24, 51, 5, 12, 35],
 [-1000, 245, 241, 300, 45, 58]]

In [45]:
cfs=np.array(nl)

In [46]:
cfs

array([[ -200,    50,    44,    42,    14,    63],
       [ -120,    24,    51,     5,    12,    35],
       [-1000,   245,   241,   300,    45,    58]])

In [47]:
type(cfs)

numpy.ndarray

In [48]:
cfs.shape

(3, 6)

In [49]:
cfs[0]

array([-200,   50,   44,   42,   14,   63])

In [50]:
cfs[-1]

array([-1000,   245,   241,   300,    45,    58])

In [51]:
cfs[1:]

array([[ -120,    24,    51,     5,    12,    35],
       [-1000,   245,   241,   300,    45,    58]])

In [52]:
cfs[:-1]

array([[-200,   50,   44,   42,   14,   63],
       [-120,   24,   51,    5,   12,   35]])

In [53]:
cfs[0][0]

-200

In [54]:
cfs[0,0]

-200

In [55]:
cfs[2,4]

45

In [56]:
cfs[2]

array([-1000,   245,   241,   300,    45,    58])

In [58]:
cfs[2,3:6]

array([300,  45,  58])

In [60]:
cfs

array([[ -200,    50,    44,    42,    14,    63],
       [ -120,    24,    51,     5,    12,    35],
       [-1000,   245,   241,   300,    45,    58]])

In [59]:
cfs[:,0]

array([ -200,  -120, -1000])

In [61]:
cfs[:,5]

array([63, 35, 58])

In [62]:
cfs[:,-1]

array([63, 35, 58])

In [63]:
cfs[:,:2]

array([[ -200,    50],
       [ -120,    24],
       [-1000,   245]])

In [68]:
cfs[:,4:]

array([[14, 63],
       [12, 35],
       [45, 58]])

In [69]:
cfs[2,1:]

array([245, 241, 300,  45,  58])

In [70]:
cfs[-2:,:2]

array([[ -120,    24],
       [-1000,   245]])

# UNEVEN CASHFLOW TERMS:

In [73]:
proj1=[-200,45,55,22,30,32]
proj2=[-1000,350,230,260,276]
proj3=[-120,23,24,53,51,64,8,11]

In [74]:
array=np.array([proj1,proj2,proj3])

C:\Users\aheed\AppData\Local\Temp\ipykernel_4436\927387246.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array=np.array([proj1,proj2,proj3])


In [75]:
array

array([list([-200, 45, 55, 22, 30, 32]),
       list([-1000, 350, 230, 260, 276]),
       list([-120, 23, 24, 53, 51, 64, 8, 11])], dtype=object)

In [76]:
array.shape

(3,)

In [77]:
#add zero cashflows to projects w less terms
proj1=[-200,45,55,22,30,32,0,0]
proj2=[-1000,350,230,260,276,0,0,0]
proj3=[-120,23,24,53,51,64,8,11]

In [127]:
proj=np.array([proj1,proj2,proj3])

In [130]:
proj

array([[ -680,   340,   230,   250,   214,     0,     0,     0],
       [-1000,   350,   230,   260,   276,     0,     0,     0],
       [ -120,    23,    24,    53,    51,    64,     8,    11]])

In [129]:
proj1=np.array([-680,340,230,250,214])

In [81]:
proj1.size

5

In [100]:
proj1.resize(8)

In [101]:
proj1

array([-680,  340,  230,  250,  214,    0,    0,    0])

In [104]:
proj

array([[ -680,   340,   230,   250,   214,     0,     0,     0],
       [-1000,   350,   230,   260,   276,     0,     0,     0],
       [ -120,    23,    24,    53,    51,    64,     8,    11]])

In [120]:
proj1[[0,3,-1]]

array([-680,  250,    0])

In [106]:
proj[[0,-1],0]

array([-680, -120])

In [108]:
proj[0,[0,2,-1]]

array([-680,  230,    0])

In [109]:
proj[[1,2],[2,4]]

array([230,  51])

In [118]:
proj2

[-1000, 350, 230, 260, 276, 0, 0, 0]

In [124]:
proj2=np.array(proj2)

In [125]:
proj2[[0,3,-1]]

array([-1000,   260,     0])

In [126]:
proj3=np.array(proj3)

In [136]:
proj[0]

array([-680,  340,  230,  250,  214,    0,    0,    0])

In [144]:
proj[[0,2],[5,7]]

array([ 0, 11])

# CHANGING ELEMENTS IN ARRAY

In [145]:
proj[:,0]=-200

In [146]:
proj

array([[-200,  340,  230,  250,  214,    0,    0,    0],
       [-200,  350,  230,  260,  276,    0,    0,    0],
       [-200,   23,   24,   53,   51,   64,    8,   11]])

In [147]:
proj[:,0]=proj[:,0]-10

In [148]:
proj

array([[-210,  340,  230,  250,  214,    0,    0,    0],
       [-210,  350,  230,  260,  276,    0,    0,    0],
       [-210,   23,   24,   53,   51,   64,    8,   11]])

In [149]:
proj[:,0]=[-220,-120,-150]

In [150]:
proj

array([[-220,  340,  230,  250,  214,    0,    0,    0],
       [-120,  350,  230,  260,  276,    0,    0,    0],
       [-150,   23,   24,   53,   51,   64,    8,   11]])

In [151]:
initial=proj[:,0]
initial

array([-220, -120, -150])

In [152]:
initial[0]=-80

In [153]:
proj

array([[ -80,  340,  230,  250,  214,    0,    0,    0],
       [-120,  350,  230,  260,  276,    0,    0,    0],
       [-150,   23,   24,   53,   51,   64,    8,   11]])

In [154]:
proj5=proj[:,-1].copy()
proj5

array([ 0,  0, 11])

In [157]:
proj5[0]=45

In [158]:
proj5[1]=-2

In [159]:
proj5

array([45, -2, 11])

In [160]:
proj

array([[ -80,  340,  230,  250,  214,    0,    0,    0],
       [-120,  350,  230,  260,  276,    0,    0,    0],
       [-150,   23,   24,   53,   51,   64,    8,   11]])

# ROW COLUMN WISE OPERATIONS

axis=0 for columns

axis=1 for rows

In [161]:
proj

array([[ -80,  340,  230,  250,  214,    0,    0,    0],
       [-120,  350,  230,  260,  276,    0,    0,    0],
       [-150,   23,   24,   53,   51,   64,    8,   11]])

In [197]:
np.sum(proj,axis=0) #0 for column axis

array([-350,  713,  484,  563,  541,   64,    8,   11])

In [167]:
np.sum(proj,axis=1) #for row axis=1

array([954, 996,  84])

In [168]:
np.cumsum(proj,axis=1)

array([[ -80,  260,  490,  740,  954,  954,  954,  954],
       [-120,  230,  460,  720,  996,  996,  996,  996],
       [-150, -127, -103,  -50,    1,   65,   73,   84]], dtype=int32)

In [169]:
np.mean(proj,axis=1)

array([119.25, 124.5 ,  10.5 ])

In [170]:
np.mean(proj,axis=0)

array([-116.66666667,  237.66666667,  161.33333333,  187.66666667,
        180.33333333,   21.33333333,    2.66666667,    3.66666667])

In [171]:
np.mean(proj)

84.75

# RESHAPING AND TRANSPOSING

In [172]:
project_1 = [-200, 20, 50, 70, 100, 50, 0, 0]
project_2 = [-50, 10, 25, 25, 50, 0, 0, 0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [173]:
projects = np.array([project_1, project_2, project_3])

In [174]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [175]:
projects.shape

(3, 8)

In [176]:
projects.reshape(8,3)

array([[ -200,    20,    50],
       [   70,   100,    50],
       [    0,     0,   -50],
       [   10,    25,    25],
       [   50,     0,     0],
       [    0, -1000,   200],
       [  200,   300,   500],
       [  500,   750,   250]])

In [177]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [179]:
projects.reshape((8,3),order='f')

array([[ -200,   200,     0],
       [  -50,    70,   500],
       [-1000,    25,     0],
       [   20,   300,     0],
       [   10,   100,   750],
       [  200,    50,     0],
       [   50,   500,     0],
       [   25,    50,   250]])

transposing: moving project from row to column

In [181]:
projects.transpose()

array([[ -200,   -50, -1000],
       [   20,    10,   200],
       [   50,    25,   200],
       [   70,    25,   300],
       [  100,    50,   500],
       [   50,     0,   500],
       [    0,     0,   750],
       [    0,     0,   250]])

In [182]:
projects.T

array([[ -200,   -50, -1000],
       [   20,    10,   200],
       [   50,    25,   200],
       [   70,    25,   300],
       [  100,    50,   500],
       [   50,     0,   500],
       [    0,     0,   750],
       [    0,     0,   250]])

# CREATE 2D ARRAY FROM SCRATCH

CREATE EMPTY ARRAY WHEN WE DONT KNOW THE ELEMENTS BUT KNOW THE SIZE, FOR EG WE HAVE 3 PROJECTS W 8 TIMESPANS

In [184]:
np.set_printoptions(precision=2, suppress= True)

In [185]:
np.empty((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [186]:
np.ones((3,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [187]:
np.zeros((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [193]:
throw=10
sim=20

In [194]:
simul=np.random.randint(1,7,throw*sim).reshape(sim,throw)
simul

array([[1, 3, 5, 3, 3, 6, 2, 6, 3, 4],
       [3, 3, 6, 4, 3, 3, 4, 6, 5, 4],
       [1, 4, 4, 4, 3, 5, 6, 5, 3, 3],
       [2, 1, 1, 5, 6, 5, 3, 3, 6, 5],
       [5, 3, 5, 3, 2, 2, 5, 1, 2, 5],
       [1, 6, 5, 5, 5, 3, 6, 5, 4, 5],
       [2, 2, 5, 3, 2, 6, 6, 4, 5, 5],
       [3, 5, 4, 3, 1, 6, 3, 3, 5, 5],
       [6, 4, 1, 1, 6, 2, 6, 5, 5, 5],
       [4, 2, 2, 4, 5, 2, 1, 2, 5, 4],
       [3, 4, 4, 5, 6, 5, 4, 1, 6, 2],
       [3, 5, 4, 3, 4, 1, 5, 6, 3, 3],
       [3, 6, 5, 2, 4, 4, 2, 4, 6, 1],
       [6, 1, 1, 3, 6, 2, 5, 1, 1, 3],
       [3, 4, 1, 1, 1, 2, 3, 1, 2, 4],
       [4, 2, 6, 3, 6, 1, 4, 4, 2, 2],
       [1, 1, 2, 3, 2, 1, 6, 6, 3, 4],
       [6, 4, 6, 3, 5, 5, 4, 3, 2, 5],
       [5, 5, 6, 5, 4, 6, 3, 6, 5, 3],
       [3, 4, 4, 4, 2, 3, 4, 2, 3, 1]])

In [195]:
simul.mean(axis=1)

array([3.6, 4.1, 3.8, 3.7, 3.3, 4.5, 4. , 3.8, 4.1, 3.1, 4. , 3.7, 3.7,
       2.9, 2.2, 3.4, 2.9, 4.3, 4.8, 3. ])

In [196]:
simul.mean(axis=0)

array([3.25, 3.45, 3.85, 3.35, 3.8 , 3.5 , 4.1 , 3.7 , 3.8 , 3.65])

# ARITHMETIC AND VECTORIZED OPERATIONS

In [198]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

matrix and scalar:

In [199]:
projects*1.1

array([[ -220. ,    22. ,    55. ,    77. ,   110. ,    55. ,     0. ,
            0. ],
       [  -55. ,    11. ,    27.5,    27.5,    55. ,     0. ,     0. ,
            0. ],
       [-1100. ,   220. ,   220. ,   330. ,   550. ,   550. ,   825. ,
          275. ]])

In [200]:
projects[0]=projects[0]*1.1

In [201]:
projects

array([[ -220,    22,    55,    77,   110,    55,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

# matrix and vector

In [202]:
a=np.array([10,20,30])

In [204]:
projects+a

ValueError: operands could not be broadcast together with shapes (3,8) (3,) 

In [205]:
a=a.reshape((3,1))

In [206]:
projects+a

array([[-210,   32,   65,   87,  120,   65,   10,   10],
       [ -30,   30,   45,   45,   70,   20,   20,   20],
       [-970,  230,  230,  330,  530,  530,  780,  280]])

In [207]:
projects.shape

(3, 8)

In [208]:
b=np.array([5,10,15,20,25,30,35,40])

In [209]:
b.shape

(8,)

In [211]:
projects

array([[ -220,    22,    55,    77,   110,    55,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [210]:
projects+b

array([[-215,   32,   70,   97,  135,   85,   35,   40],
       [ -45,   20,   40,   45,   75,   30,   35,   40],
       [-995,  210,  215,  320,  525,  530,  785,  290]])

# KEEPDIM PARAMETER

In [212]:
np.set_printoptions(precision=2, suppress= True)

In [213]:
project_1 = [-200, 20, 50, 70, 100, 50, 0, 0]
project_2 = [-50, 10, 25, 25, 50, 0, 0, 0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [214]:
projects = np.array([project_1, project_2, project_3])
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [215]:
inflows = projects[:, 1:].copy()
inflows

array([[ 20,  50,  70, 100,  50,   0,   0],
       [ 10,  25,  25,  50,   0,   0,   0],
       [200, 200, 300, 500, 500, 750, 250]])

In [218]:
total=inflows.sum(axis=1)
total

array([ 290,  110, 2700])

In [219]:
inflows/total.reshape(3,1)

array([[0.07, 0.17, 0.24, 0.34, 0.17, 0.  , 0.  ],
       [0.09, 0.23, 0.23, 0.45, 0.  , 0.  , 0.  ],
       [0.07, 0.07, 0.11, 0.19, 0.19, 0.28, 0.09]])

ALTERNATIVE METHOD:

In [221]:
inflows.sum(axis=1,keepdims=True)

array([[ 290],
       [ 110],
       [2700]])

In [220]:
inflows/inflows.sum(axis=1,keepdims=True)

array([[0.07, 0.17, 0.24, 0.34, 0.17, 0.  , 0.  ],
       [0.09, 0.23, 0.23, 0.45, 0.  , 0.  , 0.  ],
       [0.07, 0.07, 0.11, 0.19, 0.19, 0.28, 0.09]])

# ADDING AND REMOVING ELEMENTS

In [222]:
cf = np.array([-1000, 200, 200, 300, 500, 500, 750, 25])
cf

array([-1000,   200,   200,   300,   500,   500,   750,    25])

In [223]:
np.append(cf,10)

array([-1000,   200,   200,   300,   500,   500,   750,    25,    10])

In [224]:
cf

array([-1000,   200,   200,   300,   500,   500,   750,    25])

In [227]:
np.insert(cf,obj=0,values=0)

array([    0, -1000,   200,   200,   300,   500,   500,   750,    25])

In [228]:
cf

array([-1000,   200,   200,   300,   500,   500,   750,    25])

In [230]:
np.delete(cf,0)

array([200, 200, 300, 500, 500, 750,  25])

In [231]:
cf

array([-1000,   200,   200,   300,   500,   500,   750,    25])

In [232]:
cf[1:]

array([200, 200, 300, 500, 500, 750,  25])

In [233]:
np.delete(cf,[0,7])

array([200, 200, 300, 500, 500, 750])

# MERGING AND CONCATENATING

In [234]:
project_1 = [-200, 20, 50, 70, 100, 50, 0, 0]
project_2 = [-50, 10, 25, 25, 50, 0, 0, 0]
project_3 = [-1000, 200, 200, 300, 500, 500, 750, 250]

In [235]:
projects = np.array([project_1, project_2, project_3])
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250]])

In [236]:
t8=np.array([0,0,200]).reshape(3,1)
t8

array([[  0],
       [  0],
       [200]])

In [239]:
np.hstack((projects,t8))

array([[ -200,    20,    50,    70,   100,    50,     0,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250,   200]])

In [242]:
p4=[-100,20,30,50,100,70,50,0]

In [246]:
projects=np.vstack((projects,p4))

In [247]:
projects

array([[ -200,    20,    50,    70,   100,    50,     0,     0],
       [  -50,    10,    25,    25,    50,     0,     0,     0],
       [-1000,   200,   200,   300,   500,   500,   750,   250],
       [ -100,    20,    30,    50,   100,    70,    50,     0]])